export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_ID_PRODUCTS = "GET_ID_PRODUCTS"
export const ADD_PRODUCTS = "ADD_PRODUCTS" 
export const ADD_PRODUCTS_CART = "ADD_PRODUCTS_CART"
export const DELETE_PRODUCTS_CART = 'DELETE_PRODUCTS_CART'

export const CHANGE_FROM_CART = 'CHANGE_FROM_CART'
export const GET_RECIPES = "GET_RECIPES"
export const ADD_RECIPES = "ADD_RECIPES" 

export const CLEAN_PRODUCT = 'CLEAN_PRODUCT'
 
export const GET_ID_RECIPES = "GET_ID_RECIPES" 
export const CLEAN_RECIPE = "CLEAN_RECIPE" 

export const DELETE_PRODUCT_ADMIN = "DELETE_PRODUCT_ADMIN"




